#!/usr/bin/env bash
# Copy configs from this repo into the right locations on the system.
# Existing files are backed up to <file>.bak-YYYYMMDD-HHMMSS before overwrite.
#
# Usage:
#   bash apply-configs.sh                      # prompts for git identity
#   GIT_NAME="Ray Lu" GIT_EMAIL=me@example.com MACHINE=personal|work \
#     bash apply-configs.sh                    # non-interactive (agents, CI)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CFG="$SCRIPT_DIR/configs"
STAMP="$(date +%Y%m%d-%H%M%S)"

backup_and_copy() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  if [[ -e "$dst" && ! -L "$dst" ]]; then
    cp "$dst" "$dst.bak-$STAMP"
    echo "  backed up $dst -> $dst.bak-$STAMP"
  fi
  cp "$src" "$dst"
  echo "  wrote $dst"
}

# Resolve this machine's git identity and whether it's a work machine, then write
# ~/.gitconfig.local + ~/.zshrc.local. Both are untracked and per-machine, so the
# repo never carries one laptop's identity onto another.
#
# Identity comes from GIT_NAME/GIT_EMAIL/MACHINE if set, otherwise from prompts.
# If ~/.gitconfig.local already exists it is kept as the source of truth for both
# files -- including whether this is a work machine -- so that re-runs never
# leave git and zsh disagreeing about it.
setup_local() {
  local name email is_work

  if [[ -f "$HOME/.gitconfig.local" ]]; then
    echo "  ~/.gitconfig.local exists, leaving it alone"
    echo "     (delete it and re-run to change identity)"
    # Derive work-ness from the existing file rather than re-asking, so
    # ~/.zshrc.local below stays consistent with it.
    if grep -qF "$CFG/gitconfig.work" "$HOME/.gitconfig.local"; then
      is_work=y
    else
      is_work=n
    fi
  else
    if [[ -n "${GIT_NAME:-}" && -n "${GIT_EMAIL:-}" && -n "${MACHINE:-}" ]]; then
      name="$GIT_NAME"
      email="$GIT_EMAIL"
      case "$MACHINE" in
        work)     is_work=y ;;
        personal) is_work=n ;;
        *) echo "  ERROR: MACHINE must be 'work' or 'personal', got '$MACHINE'" >&2; exit 1 ;;
      esac
      echo "  using GIT_NAME/GIT_EMAIL/MACHINE from the environment ($MACHINE)"
    else
      # Reads work from a terminal or from piped input. On EOF (no terminal and
      # nothing piped, e.g. an agent or CI run) point at the env-var form
      # instead of dying on an unhelpful read failure.
      no_input() {
        echo "  ERROR: ran out of input while asking for git identity." >&2
        echo "         No terminal? Set GIT_NAME, GIT_EMAIL and MACHINE=work|personal." >&2
        exit 1
      }
      read -r -p "  git user.name: " name  || no_input
      read -r -p "  git user.email: " email || no_input
      if [[ -z "$name" || -z "$email" ]]; then
        echo "  ERROR: name and email are both required" >&2
        exit 1
      fi
      read -r -p "  Work machine? Adds Trend Micro git/go rules [y/N]: " is_work || no_input
    fi

    {
      echo "# Generated by apply-configs.sh on $STAMP. Not tracked in the dotfiles repo."
      echo "[user]"
      echo "	name = $name"
      echo "	email = $email"
      if [[ "$is_work" =~ ^[Yy]$ ]]; then
        echo "[include]"
        echo "	path = $CFG/gitconfig.work"
      fi
    } > "$HOME/.gitconfig.local"
    echo "  wrote $HOME/.gitconfig.local"
  fi

  # Always (re)written, so it can't drift from ~/.gitconfig.local.
  {
    echo "# Generated by apply-configs.sh on $STAMP. Not tracked in the dotfiles repo."
    if [[ "$is_work" =~ ^[Yy]$ ]]; then
      echo "source \"$CFG/zshrc.work\""
    fi
  } > "$HOME/.zshrc.local"
  echo "  wrote $HOME/.zshrc.local"
}

echo "==> Per-machine git identity"
setup_local

echo "==> Applying configs"
backup_and_copy "$CFG/zshrc"                    "$HOME/.zshrc"
backup_and_copy "$CFG/gitconfig"                "$HOME/.gitconfig"
backup_and_copy "$CFG/nvim/init.lua"            "$HOME/.config/nvim/init.lua"
backup_and_copy "$CFG/ghostty/config"           "$HOME/.config/ghostty/config"
backup_and_copy "$CFG/starship.toml"            "$HOME/.config/starship.toml"
backup_and_copy "$CFG/fastfetch/config.jsonc"   "$HOME/.config/fastfetch/config.jsonc"
backup_and_copy "$CFG/fastfetch/r-logo.txt"     "$HOME/.config/fastfetch/r-logo.txt"
backup_and_copy "$CFG/git_global_ignore"        "$HOME/.config/git/ignore"

echo "==> Done. Open a new terminal so .zshrc takes effect."
